# Day 03

# Python

## Coding Style

Programming style is a set of rules or guidelines used when writing the source code for a computer program. It is often claimed that following a particular programming style will help programmers to read and understand source code conforming to the style, and help to avoid introducing errors.

EX:

In [1]:
1+1

2

In [2]:
1 + 1

2

가독성이 좋도록 한 칸의 여백을 두도록 한다.

* 코드의 처음과 마지막에는 빈칸을 넣지 않는다.
* 빈칸은 항상 하나만 넣는다.
* 숫자나 연산 기호 사이는 한 칸을 띄운다.
* 괄호를 연 직후나 닫기 직전에는 빈칸을 넣지 않는다.

** 파이썬의 경우 PEP 8을 통해 Tab대신 Space를 사용하라고 되어있다. 이를 따르도록 한다. PEP 8을 참고하도록 한다.**

Indentation = 4 spaces

---
Tabs or Spaces?
Spaces are the preferred indentation method.

Tabs should be used solely to remain consistent with code that is already indented with tabs.

Python 3 disallows mixing the use of tabs and spaces for indentation.

Python 2 code indented with a mixture of tabs and spaces should be converted to using spaces exclusively.

When invoking the Python 2 command line interpreter with the -t option, it issues warnings about code that illegally mixes tabs and spaces. When using -tt these warnings become errors. These options are highly recommended!

---

**Method Names and Instance Variables**

Use the function naming rules: lowercase with words separated by underscores as necessary to improve readability.


* If operators with different priorities are used, consider adding whitespace around the operators with the lowest priority(ies). Use your own judgment; however, never use more than one space, and always have the same amount of whitespace on both sides of a binary operator.

```
Yes:

i = i + 1
submitted += 1
x = x*2 - 1
hypot2 = x*x + y*y
c = (a+b) * (a-b)

No:

i=i+1
submitted +=1
x = x * 2 - 1
hypot2 = x * x + y * y
c = (a + b) * (a - b)
```

* Don't use spaces around the = sign when used to indicate a keyword argument or a default parameter value.

```
Yes:

def complex(real, imag=0.0):
    return magic(r=real, i=imag)
    
No:

def complex(real, imag = 0.0):
    return magic(r = real, i = imag)
    
```

In [3]:
print(1//3)
print(1/3)

0
0.3333333333333333


## Slash, Backslash

우리나라는 원화기호를 넣기위해 Backslash대신 원화기호를 사용하였다.

In [4]:
 -4%10

6

In [5]:
-4/10

-0.4

연습문제 1

In [6]:
3*2-8/4

4.0

In [7]:
25*6/3+17

67.0

In [8]:
39021-276920/12040

38998.0

In [9]:
2**6-10%6

60

* 괄호: Bracket
* 대괄호: Square Bracket 
* 중괄호: Brace
* 소괄호: Parenthesis

In [10]:
True

True

In [11]:
False

False

In [12]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


**Python의 경우 특수기호로 underscore만을 사용한다**

In [14]:
a=4
( a > 0 ) & (a <= 10)

True

In [15]:
type(10/4)

float

In [16]:
2e-3

0.002

In [17]:
0.1+0.2==0.3

False

In [18]:
0.1+0.2

0.30000000000000004

In [19]:
round(0.1 + 0.2, 5) == round(0.3, 5)

True

## 이진 부동소수점 실수와 표현 오차

이진수 부동소수점 방식의 문제점은 십진수로 간단히 표현되는 소수도 이진수에서는 무한개의 유효숫자를 가지는 소수가 될 수 있다는 점이다. 예를 들어 $0.1$이라는 숫자는 십진수로는 간단히 표현되지만 이진수로 나타내면 다음과 같이  $0011_{(2)}$이 무한히 반복되는 소수가 된다.

\begin{equation}
0.1 = 0.00011001100110011001100110011001100110011001100110011001100110011\cdots_{(2)}
\end{equation}

그런데 컴퓨터에서는 하나의 숫자를 나타내기 위한 메모리 크기, 정확하게는 유효숫자에 할당된 메모리 비트(bit) 수가 제한되어 있기 때문에 특정 소수점이하는 생략하여 가장 비슷한 숫자로 표현할 수 밖에 없다. 파이썬에서는  $0.1$ 이 실제로는 가장 비슷한 다음과 같은 숫자로 저장된다.

\begin{equation}
0.1 \approx 0.1000000000000000055511151231257827021181583404541015625 
\end{equation}

In [21]:
0.1

0.1

그 이유는 REPL 방식에서 값이 출력될 때는 편의상 일정 소수점 이하를 생략하고 보여주기 때문이다. 만약 IPython이나 주피터 노트북에서 소수점 이하 55자리까지 보고 싶으면 다음과 같은 매직 명령어를 사용한다.

In [30]:
%precision 55

'%.55f'

In [31]:
0.1

0.1000000000000000055511151231257827021181583404541015625

In [32]:
# Regular 표현으로 돌아가라
%precision %r 

'%r'

***따라서 컴퓨터 연산에서 실수의 계산은 항상 오차를 가질 수 있기 때문에 실수의 계산결과를 다룰 때는 주의해야 한다. 예를 들어  0.1+0.2=0.30.1+0.2=0.3  이지만 이를 비교 연산으로 하면 다음과 같이 양변이 다르다는 결과를 보인다.***

In [33]:
0.1 + 0.2 == 0.3

False

따라서 실수를 비교할 때는 다음과 같이 `round` 명령을 사용하여 유효 숫자를 지정한 반올림을 한 후에 비교해야 한다. `round` 명령은 두번째 인수로 반올림할 소수점 이하의 유효숫자의 갯수를 받는다. 다음 명령은 소수점 5자리까지 비교한다.

In [34]:
round(0.1 + 0.2, 5) == round(0.3, 5)

True

In [41]:
round((0.1 + 0.2) - 0.3, 5) == 0.0

True

In [36]:
a = 0.3

In [37]:
a

0.3

In [38]:
%precision 55

'%.55f'

In [39]:
a

0.2999999999999999888977697537484345957636833190917968750

In [40]:
%precision %r 

'%r'

### Type Conversion

In [43]:
float(10)

10.0

In [44]:
int(10.0)

10

In [46]:
str(10)

'10'

In [49]:
float("NaN")

nan

In [50]:
float("inf")

inf

In [54]:
import numpy as np
np.nan

nan

In [55]:
type(np.nan)

float

In [58]:
x = np.array([0])

In [59]:
x

array([0])

In [62]:
-1/x

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([-inf])

In [61]:
x/x

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan])

**연습문제2**

## 따옴표를 인쇄하기

파이썬에서 두 가지 종류의 다른 따옴표를 쓸 수 있는 이유는 문자열 안에 따옴표가 들어가는 경우가 있기 때문이다. 만약 따옴표로 둘러싸인 문자열에 따옴가 포함되어 있다면 파이썬은 그 부분에서 문자열이 끝난다고 인식하기 때문에 오류가 발생한다.

이렇게 문자열 안에 큰 따옴표가 있어야 하는 경우에는 전체 문자열을 작은 따옴표로 둘러싸면 된다.

In [88]:
print('둘리가 "호이!"하고 말했어요.')

둘리가 "호이!"하고 말했어요.


In [90]:
print("둘리가 \"호이!\"하고 말했어요.")

둘리가 "호이!"하고 말했어요.


In [91]:
print("둘리가 '이제 어디로 가지?'하고 생각했어요.")

둘리가 '이제 어디로 가지?'하고 생각했어요.


In [66]:
print("""Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.""")

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.


In [96]:
string_1 = "@"*6 + "\n"
string_2 = "@    @\n"
print(string_1+string_2*3+string_1)

@@@@@@
@    @
@    @
@    @
@@@@@@



## Formatted Print

In [99]:
"My name is %s" % "Tom"

'My name is Tom'

In [100]:
"I am %d years old" % 12

'I am 12 years old'

In [101]:
"%f is the value of pi" % 3.141592

'3.141592 is the value of pi'

In [102]:
"%d times %d is %d" % (2, 3, 6)

'2 times 3 is 6'

In [103]:
"%s's score is %d" % ("Jane", 100)

"Jane's score is 100"

|형식 표시 문자열|의미|
|---|---|
|`%s`|문자열|
|`%d`|정수|
|`%f`|부동소수점 실수|
|`%20s`|전체 20칸을 차지하는 문자열(공백을 앞에 붙인다.)|
|`%-10d`|전체 20칸을 차지하는 숫자(공백을 뒤에 붙인다.)|
|`%.5f`|부동소수점의 소숫점 아래 5자리까지 표시|

In [107]:
"[%20s]" % "***"

'[                 ***]'

In [108]:
"[%20s]" % "************************************************************"

'[************************************************************]'

In [115]:
"%.2f" % (2/3)

'0.67'

## `format`매서드를 사용한 문자열 형식화

In [104]:
"My name is {}".format("Tom")

'My name is Tom'

In [105]:
"{}'s score is {}".format("Jane", 100)

"Jane's score is 100"

In [106]:
"{1}'s score is {0}, {0}, {0}, {0}, {0}, {0}, {0}".format(100, "Jane")

"Jane's score is 100, 100, 100, 100, 100, 100, 100"

In [109]:
"[{:20}]".format("*")

'[*                   ]'

In [110]:
"[{:>20}]".format("*")

'[                   *]'

In [129]:
"{:.5f}".format(2/3)

'0.66667'

### 파이썬 조건문 기초

**연습문제2**

In [221]:
def is_leap_year(year):
    return True if (year%4 == 0 and year%100 != 0) or (year%400 == 0) else False

In [222]:
is_leap_year(2005)

False

In [223]:
is_leap_year(2004)

True

In [224]:
is_leap_year(2100)

False

In [225]:
is_leap_year(2020)

True

**and**, **or** operator는 ***short-circuit***이다.

In [180]:
c = 6

if c >= 8:
    print("A")
elif c >=5:   
    print("B")
else:
    print("C")

B


In [183]:
def prisoner_dilema(xa,xb):
    if xa == True:
        if xb == False:
            yb = 10
            ya = 0
        else:
            yb = 5
            ya = 5
    elif xb == True:
        if xa == False:
            ya = 10
            yb = 0
        else:
            yb = 5
            ya = 5
    else:
        ya = 1
        yb = 1
    return ya, yb

In [184]:
prisoner_dilema(True,True)

(5, 5)

In [186]:
prisoner_dilema(True,False)

(0, 10)

In [187]:
prisoner_dilema(False,False)

(1, 1)

In [188]:
False == 0

True

In [190]:
True == 1

True

In [191]:
True == 2

False

Numpy에서는 **logical OR**을 사용하지 않는다

In [229]:
1 in [1,3,5,6,9]

True

In [231]:
def days2(year, month):
    if month in [1,3,5,7,8,10,12]:
        return 31
    elif month == 2:
        if is_leap_year(year):
            return 29
        else:
            return 28
    else:
        return 30

In [232]:
days2(2017,5)

31

In [233]:
days2(2017,2)

28

In [234]:
days2(2016,2)

29

In [235]:
days2(2017,8)

31

## 지역 변수

함수에 넣은 입력 변수나 함수 안에서 만들어진 변수는 함수 바깥에서는 사용할 수 없다. 혹시 이름이 같은 변수가 있다고 하더라도 별개의 변수가 된다.

따라서 함수 안에서 만들어지고 사용되는 함수를 지역 변수, 영어로 local variable 이라고 한다.

## 전역 변수

하지만 지역 변수와 반대로 함수 바깥에서 만들어진 변수는 함수 안에서 사용할 수 있다.
다만 이 때 바깥의 변수와 같은 이름의 변수를 함수 안에 만들면 안된다.

만약 바깥의 변수와 같은 이름의 변수를 함수 안에 다시 만들면 함수 안에서는 그 지역 변수를 사용하다가 함수 바깥으로 나오면 지역 변수는 사라지고 원래의 변수값으로 되돌아 온다.

따라서, 함수 안에서는 함수 바깥에 있는 변수의 값을 바꿀 수 없다.

만약 함수안에서 함수 바깥에 있는 변수의 값을 꼭 바꿔야만 한다면 다음과 같이 함수 이름 앞에 `global` 키워드를 선언해 주면 된다.

## for 반복문

```
for 카운터변수 in range(반복횟수):
    반복해서 실행할 명령
```

이 때 반복횟수는 10, 100과 같은 양의 정수이어야 하고 카운터 변수의 이름은 아무거나 쓸 수 있다. 하지만 전문 프로그래머들은 보통 `i` 또는 `j` 라는 변수 이름을 자주 사용한다.

In [239]:
for i in range(10):
    print("=")

=
=
=
=
=
=
=
=
=
=


In [240]:
for i in range(10):
    print("=" + str(i) + "=")

=0=
=1=
=2=
=3=
=4=
=5=
=6=
=7=
=8=
=9=


In [241]:
for i in range(9):
    print("=" + str(i + 1) + "=")

=1=
=2=
=3=
=4=
=5=
=6=
=7=
=8=
=9=


**연습문제**

In [248]:
for i in range(10):
    print("*"*i)


*
**
***
****
*****
******
*******
********
*********


In [250]:
for i in range(10):
    print("*"*(10-1-i))

*********
********
*******
******
*****
****
***
**
*



In [255]:
for i in range(20):
    if i < 10:
        print("*"*i)
    else:
        print("*"*(20-i))


*
**
***
****
*****
******
*******
********
*********
**********
*********
********
*******
******
*****
****
***
**
*


In [335]:
def rangoli(n):
    for i in range(n):
        if i <= int(n/2):
            print(" "*(int(n/2)-i) + "*"*(2*i+1))
        else: 
            print(" "*(i-int(n/2)) + "*"*(n-2*(i-int(n/2))))

In [336]:
rangoli(11)

     *
    ***
   *****
  *******
 *********
***********
 *********
  *******
   *****
    ***
     *
