# Day 13

**연습문제 2**
NumPy를 사용해서 붓꽃 데이터  x2 에 대한 벡터 변수 x2를 만든다.

In [1]:
import numpy as np

In [5]:
x2 = np.array([4.9,3.0,1.4,0.2])

In [6]:
x2 = x2[:,np.newaxis]

In [7]:
x2

array([[ 4.9],
       [ 3. ],
       [ 1.4],
       [ 0.2]])

In [8]:
x1 = np.array([5.1,3.5,1.4,0.2])
x1 = x1[:,np.newaxis]
x1

array([[ 5.1],
       [ 3.5],
       [ 1.4],
       [ 0.2]])

In [16]:
print(x1.T.shape)
print(x2.T.shape)

(1, 4)
(1, 4)


In [20]:
print(x1.T)
print(x2.T)

[[ 5.1  3.5  1.4  0.2]]
[[ 4.9  3.   1.4  0.2]]


In [25]:
X = np.concatenate([x1.T,x2.T])
X

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2]])

In [27]:
X.T

array([[ 5.1,  4.9],
       [ 3.5,  3. ],
       [ 1.4,  1.4],
       [ 0.2,  0.2]])

In [32]:
X[1,:].reshape(4,1)

array([[ 4.9],
       [ 3. ],
       [ 1.4],
       [ 0.2]])

In [33]:
X[:,2].reshape(2,1)

array([[ 1.4],
       [ 1.4]])

In [34]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [38]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [39]:
np.diag([1,3,5,6,77,3])

array([[ 1,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0],
       [ 0,  0,  0,  6,  0,  0],
       [ 0,  0,  0,  0, 77,  0],
       [ 0,  0,  0,  0,  0,  3]])

**연습문제 01**

In [56]:
A = np.array([[1, 2, 3],[4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [57]:
C = np.dot(A, B)
C

array([[22, 28],
       [49, 64]])

In [58]:
C = np.dot(B, A)
C

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

(3)

In [42]:
A = np.array([[1,2,3]])

In [44]:
B=np.array([[4,7],[5,8],[6,9]])

In [45]:
np.dot(A,B)

array([[32, 50]])

(4)

In [47]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [48]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [49]:
np.dot(B,A)

array([[23, 34],
       [31, 46]])

(5)

In [52]:
x=np.array([[1],[2],[3]])
x

array([[1],
       [2],
       [3]])

In [53]:
np.dot(x.T,x)

array([[14]])

In [54]:
np.dot(x,x.T)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

**연습문제 05**

In [59]:
from sympy import symbols

In [61]:
x1, x2, x3 = symbols('x1,x2,x3')

In [62]:
a11,a12,a13,a21,a22,a23,a31,a32,a33 = symbols('a11,a12,a13,a21,a22,a23,a31,a32,a33')

In [65]:
x = np.array([[x1],[x2],[x3]])
x

array([[x1],
       [x2],
       [x3]], dtype=object)

In [67]:
A = np.array([[a11,a12,a13],[a21,a22,a23],[a31,a32,a33]])
A

array([[a11, a12, a13],
       [a21, a22, a23],
       [a31, a32, a33]], dtype=object)

In [70]:
np.dot(np.dot(x.T,A),x)

array([[ x1*(a11*x1 + a21*x2 + a31*x3) + x2*(a12*x1 + a22*x2 + a32*x3) + x3*(a13*x1 + a23*x2 + a33*x3)]], dtype=object)

In [71]:
np.dot(A,x)

array([[a11*x1 + a12*x2 + a13*x3],
       [a21*x1 + a22*x2 + a23*x3],
       [a31*x1 + a32*x2 + a33*x3]], dtype=object)